<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

In [2]:
import numpy as np

### Exercise 1
1. 1 similarity between lists and arrays is that a specific item in the list/array can be selected by selecting its relevant index starting from 0.
    Another similarity is that the number of elements can be found in a list/array using len() function.
2. 1 difference between lists and array is that for lists, it works on the entire set of data whereas for arrays, it works on the individual elements.
   Another difference between lists and array is that arrays only accept one type of data whereas lists accept all.
3. A dictionary is *works similarly to lists and arrays, except it doesn't need two lines of data to hold two types of data, and it can be accessed via a key*

### Exercise 2

In [3]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


### Exercise 3

In [5]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']

print(elements[4])
print(elements[-4])

Boron
Nitrogen


### Exercise 4

In [13]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
np_array = np.array([45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]    )

In [12]:
sum(np_array == 1)

np.int64(9)

### Exercise 5"

In [78]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

np_array_1 = np.array(x_1)
np_array_2 = np.array(x_2)
print(np_array_1)

[  1   4   9  16  25  36  49  64  81 100]


In [17]:
mean1=float(np.mean(np_array_1))
mean2=float(np.mean(np_array_2))

print(mean1,type(mean1))
print(mean2,type(mean2))



38.5 <class 'float'>
302.5 <class 'float'>


In [58]:
S1 = np.std(np_array_1)
S2 = np.std(np_array_2)
print(S1)
print(S2)


32.41990129534635
326.0893282522444


In [47]:
sum1=int(np.sum(np_array_1))
sum2=int(np.sum(np_array_2))

print(sum1, type(sum1))
print(sum2, type(sum2))

385 <class 'int'>
3025 <class 'int'>


In [91]:
covariance=np.mean((np_array_1 - mean1)*(np_array_2 - mean2))
print(covariance)

10436.25


In [92]:
covariance/[(S1)*(S2)]

array([0.98717966])

In [96]:
np.corrcoef(np_array_1, np_array_2)

array([[1.        , 0.98717966],
       [0.98717966, 1.        ]])