<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1
1. Subsetting means selecting something
2. Indexing is a form of subsetting where you select a specific element
3. Slicing is a form of subsetting where you select a series of elements
4. Masking is when you choose to display or not display certain elements

### Exercise 2

In [3]:
import numpy as np

In [27]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
x=np_array_2d
y=x[:,0].copy()
print(y)

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


In [25]:
y.astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [12]:
y.astype(int)%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [14]:
my_mask=y.astype(int)%2 != 0
my_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [17]:
x[:,1][my_mask]   #in the array, 0 index are the numbers and 1 index are the letters

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### Exercise 3

In [56]:
x=np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [92]:
x[x>50]=1
x[x==50]=0

In [93]:
x

array([[ 1,  0,  1, -1, -1],
       [ 1, -1,  1, -1, -1],
       [ 1, -1, -1,  1, -1],
       [-1,  1,  1, -1, -1],
       [ 1, -1,  1, -1,  1]])